-- MySQL Script generated by MySQL Workbench
-- Tue Jan 26 00:25:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plusprime
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plusprime` DEFAULT CHARACTER SET utf8 ;
USE `plusprime` ;


-- -----------------------------------------------------
-- Table `plusprime`.`SUSCRIPCIÓN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`SUSCRIPCION` (
  `Suscripcion` INT NOT NULL AUTO_INCREMENT,
  `Precio` FLOAT NOT NULL,
  `Numero_pantallas` INT NOT NULL,
  `Numero_perfiles` INT NOT NULL,
  `Calidad` VARCHAR(10) NULL,
  PRIMARY KEY (`Suscripcion`));

-- -----------------------------------------------------
-- Table `plusprime`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`CLIENTE` (
  `Email` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NULL,
  `Pais` VARCHAR(2) NULL,
  `Suscripcion` INT NOT NULL,
  PRIMARY KEY (`Email`, `Suscripcion`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  INDEX `fk_Cliente_Suscripción_idx` (`Suscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Suscripción`
    FOREIGN KEY (`Suscripcion`)
    REFERENCES `plusprime`.`SUSCRIPCION` (`Suscripcion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`PERFIL` (
  `Nombre` VARCHAR(40) NOT NULL,
  `Infantil` INT NULL,
  `Cliente_Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Nombre`, `Cliente_Email`),
  INDEX `fk_Perfil_Cliente1_idx` (`Cliente_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Cliente1`
    FOREIGN KEY (`Cliente_Email`)
    REFERENCES `plusprime`.`CLIENTE` (`Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`PELICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`PELICULA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Valoracion` INT NULL DEFAULT 0,
  `Visualizaciones` INT NULL DEFAULT 0,
  `Genero` VARCHAR(45) NOT NULL,
  `Exclusivo` INT NOT NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`ID`));



-- -----------------------------------------------------
-- Table `plusprime`.`SERIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`SERIE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Valoracion` INT NULL DEFAULT 0,
  `Visualizaciones` INT NULL DEFAULT 0,
  `Genero` VARCHAR(45) NOT NULL,
  `Exclusivo` INT NOT NULL,
  `Precio` FLOAT NULL,
  `Num_temporadas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`));



-- -----------------------------------------------------
-- Table `plusprime`.`ALQUILER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`ALQUILER` (
  `Pelicula_ID` INT NOT NULL,
  `Cliente_Email` VARCHAR(50) NOT NULL,
  `Fecha_adquisicion` DATETIME NOT NULL,
  `Fecha_caducidad` DATETIME NOT NULL,
  `Serie_ID` INT NOT NULL,
  PRIMARY KEY (`Pelicula_ID`, `Cliente_Email`, `Fecha_adquisicion`, `Fecha_caducidad`, `Serie_ID`),
  INDEX `fk_Pelicula_has_Cliente_Cliente1_idx` (`Cliente_Email` ASC) VISIBLE,
  INDEX `fk_Pelicula_has_Cliente_Pelicula1_idx` (`Pelicula_ID` ASC) VISIBLE,
  INDEX `fk_Alquiler_Serie1_idx` (`Serie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pelicula_has_Cliente_Pelicula1`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `plusprime`.`PELICULA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pelicula_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_Email`)
    REFERENCES `plusprime`.`CLIENTE` (`Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alquiler_Serie1`
    FOREIGN KEY (`Serie_ID`)
    REFERENCES `plusprime`.`SERIE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`TEMPORADAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`TEMPORADAS` (
  `Num_temporada` INT NOT NULL,
  `Total_capitulos` INT NOT NULL DEFAULT 0,
  `Serie_ID` INT NOT NULL,
  PRIMARY KEY (`Num_temporada`, `Serie_ID`),
  INDEX `fk_Temporadas_Serie1_idx` (`Serie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Temporadas_Serie1`
    FOREIGN KEY (`Serie_ID`)
    REFERENCES `plusprime`.`SERIE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`CAPITULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`CAPITULO` (
  `Num_capitulo` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Duracion` TIME NOT NULL,
  `Temporadas_Num_temporada` INT NOT NULL,
  `Temporadas_Serie_ID` INT NOT NULL,
  PRIMARY KEY (`Num_capitulo`, `Temporadas_Num_temporada`, `Temporadas_Serie_ID`),
  INDEX `fk_Capitulo_Temporadas1_idx` (`Temporadas_Num_temporada` ASC, `Temporadas_Serie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Capitulo_Temporadas1`
    FOREIGN KEY (`Temporadas_Num_temporada` , `Temporadas_Serie_ID`)
    REFERENCES `plusprime`.`TEMPORADAS` (`Num_temporada` , `Serie_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`RECOMENDADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`RECOMENDADO` (
  `Serie_ID` INT NOT NULL,
  `Pelicula_ID` INT NOT NULL,
  `Match` INT NOT NULL,
  `Perfil_Nombre` VARCHAR(40) NOT NULL,
  `Perfil_Cliente_Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Serie_ID`, `Pelicula_ID`, `Perfil_Nombre`, `Perfil_Cliente_Email`),
  INDEX `fk_Serie_has_Perfil_Serie1_idx` (`Serie_ID` ASC) VISIBLE,
  INDEX `fk_Serie_has_Perfil_Pelicula1_idx` (`Pelicula_ID` ASC) VISIBLE,
  INDEX `fk_Recomendado_Perfil1_idx` (`Perfil_Nombre` ASC, `Perfil_Cliente_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Serie_has_Perfil_Serie1`
    FOREIGN KEY (`Serie_ID`)
    REFERENCES `plusprime`.`SERIE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Serie_has_Perfil_Pelicula1`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `plusprime`.`PELICULA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recomendado_Perfil1`
    FOREIGN KEY (`Perfil_Nombre` , `Perfil_Cliente_Email`)
    REFERENCES `plusprime`.`PERFIL` (`Nombre` , `Cliente_Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `plusprime`.`FAVORITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plusprime`.`FAVORITO` (
  `Serie_ID` INT NOT NULL,
  `Perfil_Nombre` VARCHAR(40) NOT NULL,
  `Perfil_Cliente_Email` VARCHAR(50) NOT NULL,
  `Pelicula_ID` INT NOT NULL,
  PRIMARY KEY (`Serie_ID`, `Perfil_Nombre`, `Perfil_Cliente_Email`, `Pelicula_ID`),
  INDEX `fk_Serie_has_Perfil_Perfil1_idx` (`Perfil_Nombre` ASC, `Perfil_Cliente_Email` ASC) VISIBLE,
  INDEX `fk_Serie_has_Perfil_Serie2_idx` (`Serie_ID` ASC) VISIBLE,
  INDEX `fk_Favorito_Pelicula1_idx` (`Pelicula_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Serie_has_Perfil_Serie2`
    FOREIGN KEY (`Serie_ID`)
    REFERENCES `plusprime`.`SERIE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Serie_has_Perfil_Perfil1`
    FOREIGN KEY (`Perfil_Nombre` , `Perfil_Cliente_Email`)
    REFERENCES `plusprime`.`PERFIL` (`Nombre` , `Cliente_Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Favorito_Pelicula1`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `plusprime`.`PELICULA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


DELIMITER //
CREATE TRIGGER addCapitulo
    AFTER INSERT
    ON CAPITULO
    FOR EACH ROW
BEGIN
  DECLARE total_cap INT;
  SELECT Total_capitulos
  INTO @total_cap
  FROM TEMPORADAS
  WHERE TEMPORADAS.Num_temporada = NEW.Temporadas_Num_temporada
  AND TEMPORADAS.Serie_ID = NEW.Temporadas_Serie_ID;
  UPDATE TEMPORADAS
  SET Total_capitulos = @total_cap + 1
  WHERE TEMPORADAS.Num_temporada = NEW.Temporadas_Num_temporada
  AND TEMPORADAS.Serie_ID = NEW.Temporadas_Serie_ID;
END;//

CREATE TRIGGER addTemporada
    AFTER INSERT
    ON TEMPORADAS
    FOR EACH ROW
BEGIN
  DECLARE total_temp INT;
  SELECT Num_temporadas
  INTO @total_temp
  FROM SERIE
  WHERE SERIE.ID = NEW.Serie_ID;
  UPDATE SERIE
  SET Num_temporadas = @total_temp + 1
  WHERE SERIE.ID = NEW.Serie_ID;
END;//

DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
                                                                                                                                         
                              

