-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 19:42:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `coordenada_x` INT NOT NULL,
  `coordenada_Y` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Zona_Codigo_Zona` INT NOT NULL,
  `Zona_Codigo_Zona1` INT NOT NULL,
  `Zona_Codigo_Zona2` INT NOT NULL,
  PRIMARY KEY (`coordenada_x`, `coordenada_Y`, `Zona_Codigo_Zona1`));


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Codigo_Zona` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tamaño` INT NULL,
  `Vivero_coordenada_x` INT NOT NULL,
  `Vivero_coordenada_Y` INT NOT NULL,
  `Vivero_Zona_Codigo_Zona1` INT NOT NULL,
  `Zona_Codigo_Zona` INT NOT NULL,
  PRIMARY KEY (`Codigo_Zona`, `Zona_Codigo_Zona`),
  INDEX `fk_Zona_Vivero1_idx` (`Vivero_coordenada_x` ASC, `Vivero_coordenada_Y` ASC, `Vivero_Zona_Codigo_Zona1` ASC),
  CONSTRAINT `fk_Zona_Vivero1`
    FOREIGN KEY (`Vivero_coordenada_x` , `Vivero_coordenada_Y` , `Vivero_Zona_Codigo_Zona1`)
    REFERENCES `mydb`.`Vivero` (`coordenada_x` , `coordenada_Y` , `Zona_Codigo_Zona1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Numero_Seg_Social` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Dirección` VARCHAR(100) NULL,
  PRIMARY KEY (`DNI`));


-- -----------------------------------------------------
-- Table `mydb`.`Trabaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabaja` (
  `Fecha_Ini` DATE NOT NULL,
  `Empleados_DNI` VARCHAR(9) NOT NULL,
  `Zona_Codigo_Zona` INT NOT NULL,
  `Fecha_Fin` DATE NOT NULL,
  `Empleados_DNI1` VARCHAR(9) NOT NULL,
  `Zona_Codigo_Zona1` INT NOT NULL,
  PRIMARY KEY (`Fecha_Ini`, `Fecha_Fin`, `Empleados_DNI1`, `Zona_Codigo_Zona1`),
  INDEX `fk_Trabaja_Empleados1_idx` (`Empleados_DNI1` ASC),
  INDEX `fk_Trabaja_Zona1_idx` (`Zona_Codigo_Zona1` ASC),
  CONSTRAINT `fk_Trabaja_Empleados1`
    FOREIGN KEY (`Empleados_DNI1`)
    REFERENCES `mydb`.`Empleados` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabaja_Zona1`
    FOREIGN KEY (`Zona_Codigo_Zona1`)
    REFERENCES `mydb`.`Zona` (`Codigo_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Tipo` VARCHAR(45) NULL,
  `Stock` INT NULL,
  `Cod_barras` INT NOT NULL,
  `PVP` DECIMAL(2) NULL,
  PRIMARY KEY (`Cod_barras`));


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_nac` DATE NULL,
  `Cod_Fid` INT NULL,
  `Vol_Mensual` INT NULL,
  `Bonif` INT NULL,
  PRIMARY KEY (`DNI`));


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Cod_Pedido` INT NOT NULL,
  `Importe` DECIMAL(2) NULL,
  `Empleados_DNI` VARCHAR(9) NOT NULL,
  `Cliente_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Cod_Pedido`, `Empleados_DNI`, `Cliente_DNI`),
  INDEX `fk_Pedido_Empleados1_idx` (`Empleados_DNI` ASC),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_DNI` ASC),
  CONSTRAINT `fk_Pedido_Empleados1`
    FOREIGN KEY (`Empleados_DNI`)
    REFERENCES `mydb`.`Empleados` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Asigna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asigna` (
  `Zona_Zona_Codigo_Zona` INT NOT NULL,
  `Producto_Cod_barras` INT NOT NULL,
  PRIMARY KEY (`Zona_Zona_Codigo_Zona`, `Producto_Cod_barras`),
  INDEX `fk_Asigna_Producto1_idx` (`Producto_Cod_barras` ASC),
  CONSTRAINT `fk_Asigna_Zona1`
    FOREIGN KEY (`Zona_Zona_Codigo_Zona`)
    REFERENCES `mydb`.`Zona` (`Zona_Codigo_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asigna_Producto1`
    FOREIGN KEY (`Producto_Cod_barras`)
    REFERENCES `mydb`.`Producto` (`Cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Contiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contiene` (
  `Pedido_Cod_Pedido` INT NOT NULL,
  `Cantidad` INT NULL,
  `Producto_Cod_barras1` INT NOT NULL,
  INDEX `fk_Contiene_Pedido1_idx` (`Pedido_Cod_Pedido` ASC),
  PRIMARY KEY (`Pedido_Cod_Pedido`, `Producto_Cod_barras1`),
  INDEX `fk_Contiene_Producto1_idx` (`Producto_Cod_barras1` ASC),
  CONSTRAINT `fk_Contiene_Pedido1`
    FOREIGN KEY (`Pedido_Cod_Pedido`)
    REFERENCES `mydb`.`Pedido` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contiene_Producto1`
    FOREIGN KEY (`Producto_Cod_barras1`)
    REFERENCES `mydb`.`Producto` (`Cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
