-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 20:20:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Catastro` DEFAULT CHARACTER SET utf8 ;
USE `Catastro` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro`.`Zona` (
  `Codigo Postal` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo Postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro`.`Persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Persona_DNI_C.F` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`, `Persona_DNI_C.F`),
  INDEX `fk_Persona_Persona_idx` (`Persona_DNI_C.F` ASC),
  CONSTRAINT `fk_Persona_Persona`
    FOREIGN KEY (`Persona_DNI_C.F`)
    REFERENCES `Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda_Uni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro`.`Vivienda_Uni` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Cant_personas` INT NULL,
  `Persona_DNI` VARCHAR(9) NOT NULL,
  `Zona_Codigo Postal` INT NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  CONSTRAINT `fk_Vivienda_Uni_Persona`
    FOREIGN KEY (`Persona_DNI`)
    REFERENCES `Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vivienda_Uni_Zona`
    FOREIGN KEY (`Zona_Codigo Postal`)
    REFERENCES `Catastro`.`Zona` (`Codigo Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro`.`Bloque` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Cant_personas` INT NULL,
  `Zona_Codigo Postal` INT NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  INDEX `fk_Bloque_Zona_idx` (`Zona_Codigo Postal` ASC),
  CONSTRAINT `fk_Bloque_Zona`
    FOREIGN KEY (`Zona_Codigo Postal`)
    REFERENCES `Catastro`.`Zona` (`Codigo Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro`.`Piso` (
  `Bloque_Calle` VARCHAR(45) NOT NULL,
  `Bloque_Numero` INT NOT NULL,
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  `Persona_DNI_Dueño` VARCHAR(9) NOT NULL,
  `Persona_DNI_Habita` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Bloque_Calle`, `Bloque_Numero`, `Planta`, `Letra`),
  CONSTRAINT `fk_Piso_Bloque`
    FOREIGN KEY (`Bloque_Calle` , `Bloque_Numero`)
    REFERENCES `Catastro`.`Bloque` (`Calle` , `Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Persona1`
    FOREIGN KEY (`Persona_DNI_Dueño`)
    REFERENCES `Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Persona2`
    FOREIGN KEY (`Persona_DNI_Habita`)
    REFERENCES `Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
