-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 19:42:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Viveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Viveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Viveros` DEFAULT CHARACTER SET utf8 ;
USE `Viveros` ;

-- -----------------------------------------------------
-- Table `Viveros`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Vivero` (
  `coordenada_x` INT NOT NULL,
  `coordenada_Y` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`coordenada_x`, `coordenada_Y`)
);

-- -----------------------------------------------------
-- Table `Viveros`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Zona` (
  `Codigo_Zona` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tamaño` INT NULL,
  `Vivero_coordenada_x` INT NOT NULL,
  `Vivero_coordenada_Y` INT NOT NULL,
  PRIMARY KEY (`Codigo_Zona`),
  INDEX `fk_Zona_Vivero_idx` (`Vivero_coordenada_x` ASC, `Vivero_coordenada_Y` ASC),
  CONSTRAINT `fk_Zona_Vivero`
    FOREIGN KEY (`Vivero_coordenada_x`, `Vivero_coordenada_Y`)
    REFERENCES `Viveros`.`Vivero` (`coordenada_x`, `coordenada_Y`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Viveros`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Empleados` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Numero_Seg_Social` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Dirección` VARCHAR(100) NULL,
  PRIMARY KEY (`DNI`));


-- -----------------------------------------------------
-- Table `Viveros`.`Trabaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Trabaja` (
  `Fecha_Ini` DATE NOT NULL,
  `Empleados_DNI` VARCHAR(9) NOT NULL,
  `Zona_Codigo_Zona` INT NOT NULL,
  `Fecha_Fin` DATE NOT NULL,
  PRIMARY KEY (`Fecha_Ini`, `Fecha_Fin`, `Empleados_DNI`, `Zona_Codigo_Zona`),
  INDEX `fk_Trabaja_Empleados_idx` (`Empleados_DNI` ASC),
  INDEX `fk_Trabaja_Zona_idx` (`Zona_Codigo_Zona` ASC),
  CONSTRAINT `fk_Trabaja_Empleados`
    FOREIGN KEY (`Empleados_DNI`)
    REFERENCES `Viveros`.`Empleados` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabaja_Zona`
    FOREIGN KEY (`Zona_Codigo_Zona`)
    REFERENCES `Viveros`.`Zona` (`Codigo_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Viveros`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Producto` (
  `Tipo` VARCHAR(45) NULL,
  `Stock` INT NULL,
  `Cod_barras` INT NOT NULL,
  `PVP` DECIMAL(2) NULL,
  PRIMARY KEY (`Cod_barras`));


-- -----------------------------------------------------
-- Table `Viveros`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_nac` DATE NULL,
  `Cod_Fid` INT NULL,
  `Vol_Mensual` INT NULL,
  `Bonif` INT NULL,
  `Email` VARCHAR(50),
  PRIMARY KEY (`DNI`));


-- -----------------------------------------------------
-- Table `Viveros`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Pedido` (
  `Cod_Pedido` INT NOT NULL,
  `Importe` DECIMAL(2) NULL,
  `Empleados_DNI` VARCHAR(9) NOT NULL,
  `Cliente_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Cod_Pedido`),
  INDEX `fk_Pedido_Empleados_idx` (`Empleados_DNI` ASC),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_DNI` ASC),
  CONSTRAINT `fk_Pedido_Empleados`
    FOREIGN KEY (`Empleados_DNI`)
    REFERENCES `Viveros`.`Empleados` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_DNI`)
    REFERENCES `Viveros`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Viveros`.`Asigna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Asigna` (
  `Codigo_Zona` INT NOT NULL,
  `Producto_Cod_barras` INT NOT NULL,
  PRIMARY KEY (`Codigo_Zona`, `Producto_Cod_barras`),
  INDEX `fk_Asigna_Producto_idx` (`Producto_Cod_barras` ASC),
  CONSTRAINT `fk_Asigna_Zona`
    FOREIGN KEY (`Codigo_Zona`)
    REFERENCES `Viveros`.`Zona` (`Codigo_Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asigna_Producto`
    FOREIGN KEY (`Producto_Cod_barras`)
    REFERENCES `Viveros`.`Producto` (`Cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Viveros`.`Contiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Viveros`.`Contiene` (
  `Pedido_Cod_Pedido` INT NOT NULL,
  `Cantidad` INT NULL,
  `Producto_Cod_barras` INT NOT NULL,
  INDEX `fk_Contiene_Pedido_idx` (`Pedido_Cod_Pedido` ASC) ,
  PRIMARY KEY (`Pedido_Cod_Pedido`, `Producto_Cod_barras`),
  INDEX `fk_Contiene_Producto_idx` (`Producto_Cod_barras` ASC),
  CONSTRAINT `fk_Contiene_Pedido`
    FOREIGN KEY (`Pedido_Cod_Pedido`)
    REFERENCES `Viveros`.`Pedido` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contiene_Producto`
    FOREIGN KEY (`Producto_Cod_barras`)
    REFERENCES `Viveros`.`Producto` (`Cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
